[tox]
minversion = 4.28.0
envlist = py3,pep8

[testenv]
usedevelop = True
setenv =
  OS_TEST_PATH=./castellan/tests/unit
constraints =
  {env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/master}
deps =
  -r{toxinidir}/test-requirements.txt
commands = stestr run --slowest --concurrency=1 {posargs}

[testenv:pep8]
description =
  Run style checks.
deps =
  pre-commit
  {[testenv:mypy]deps}
commands =
  pre-commit run -a
  {[testenv:mypy]commands}

[testenv:mypy]
description =
  Run type checks.
deps =
  {[testenv]deps}
  mypy
commands =
  mypy --cache-dir="{envdir}/mypy_cache" {posargs:castellan}

[testenv:venv]
commands = {posargs}

[testenv:debug]
commands = oslo_debug_helper {posargs}

[testenv:cover]
setenv =
  PYTHON=coverage run --source castellan --parallel-mode
commands =
  coverage erase
  {[testenv]commands}
  coverage combine
  coverage html -d cover
  coverage xml -o cover/coverage.xml
  coverage report --show-missing

[testenv:docs]
# This environment is called from CI scripts to test and publish
# the main docs to https://docs.openstack.org/castellan
allowlist_externals = rm
description = Build main documentation
deps =
  -r{toxinidir}/doc/requirements.txt
commands=
  rm -rf doc/build doc/build/doctrees
  sphinx-build -W -b html -d doc/build/doctrees doc/source doc/build/html

[testenv:pdf-docs]
deps = {[testenv:docs]deps}
allowlist_externals =
  rm
  make
commands =
  rm -rf doc/build/pdf
  sphinx-build -W -b latex doc/source doc/build/pdf
  make -C doc/build/pdf

[testenv:releasenotes]
skip_install = true
deps = {[testenv:docs]deps}
commands = sphinx-build -a -E -W -d releasenotes/build/doctrees -b html releasenotes/source releasenotes/build/html

[testenv:functional]
setenv =
  OS_TEST_PATH=./castellan/tests/functional
commands = stestr run --slowest --concurrency=1 {posargs}

[testenv:functional-vault]
passenv = HOME
setenv =
  OS_TEST_PATH=./castellan/tests/functional
commands =
  {toxinidir}/tools/setup-vault-env.sh pifpaf -e VAULT_TEST run vault -- stestr run --concurrency=1 --slowest {posargs}
allowlist_externals =
  {toxinidir}/tools/setup-vault-env.sh

[testenv:genconfig]
commands =
  oslo-config-generator --config-file=etc/castellan/functional-config-generator.conf
  oslo-config-generator --config-file=etc/castellan/sample-config-generator.conf

[flake8]
# We only enable the hacking (H) checks
select = H
# [H106] Don't put vim configuration in source files.
# [H203] Use assertIs(Not)None to check for None.
# H904: Delay string interpolations at logging calls
enable-extensions = H106,H203,H904

[hacking]
import_exceptions =
  collections.abc
  castellan.i18n
  typing

[testenv:bindep]
skip_install = true
# Do not install any requirements. We want this to be fast and work even if
# system dependencies are missing, since it's used to tell you what system
# dependencies are missing! This also means that bindep must be installed
# separately, outside of the requirements files, and develop mode disabled
# explicitly to avoid unnecessarily installing the checked-out repo too (this
# further relies on "tox.skipsdist = True" above).
deps = bindep
commands = bindep test
usedevelop = False
